<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<<<<<<< HEAD
<testsuite hostname="CMLJAMRASINGHA" name="Default test" tests="4" failures="2" timestamp="7 Dec 2016 11:06:54 GMT" time="13.987" errors="0">
  <testcase name="GL_UM_09_1" time="0.52" classname="com.glance.usermanagement.tests.ManageUser"/>
  <testcase name="GL_UM_09_1" time="0.574" classname="com.glance.usermanagement.tests.ManageUser">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at com.glance.usermanagement.tests.ManageUser.GL_UM_09_1(ManageUser.java:69)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:100)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:646)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:811)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1129)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:746)
	at org.testng.TestRunner.run(TestRunner.java:600)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1264)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1189)
	at org.testng.TestNG.runSuites(TestNG.java:1104)
	at org.testng.TestNG.run(TestNG.java:1076)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:152)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:57)
]]>
    </failure>
  </testcase> <!-- GL_UM_09_1 -->
  <testcase name="GL_UM_09_1" time="0.522" classname="com.glance.usermanagement.tests.ManageUser"/>
  <testcase name="GL_UM_09_1" time="0.436" classname="com.glance.usermanagement.tests.ManageUser">
=======
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<testsuite hostname="CMDMITTRN2" name="Default test" tests="3" failures="0" timestamp="8 Dec 2016 07:55:25 GMT" time="5.516" errors="0">
  <testcase name="@BeforeMethod verifyGoToDeleteUserPage" time="0.0" classname="com.glance.usermanagement.tests.TestDeleteUser">
    <failure type="java.lang.Error" message="Unresolved compilation problem: 
	The declared package &amp;quot;com.glance.usermanagement.tests&amp;quot; does not match the expected package &amp;quot;com.glance.pageobjects.usermanagement&amp;quot;
">
      <![CDATA[java.lang.Error: Unresolved compilation problem: 
	The declared package "com.glance.usermanagement.tests" does not match the expected package "com.glance.pageobjects.usermanagement"

	at com.glance.pageobjects.usermanagement.DeleteUser.<init>(DeleteUser.java:1)
	at com.glance.usermanagement.tests.TestDeleteUser.verifyGoToDeleteUserPage(TestDeleteUser.java:25)
=======
<testsuite hostname="CMDMITTRN9" name="Default test" tests="7" failures="4" timestamp="8 Dec 2016 09:08:55 GMT" time="170.488" errors="0">
  <testcase name="GL_Settings_AE_09" time="1.728" classname="com.glance.dashboard.tests.VerifyAddEngagement"/>
  <testcase name="GL_Settings_AE_10" time="5.768" classname="com.glance.dashboard.tests.VerifyAddEngagement"/>
  <testcase name="GL_Settings_AE_11" time="3.022" classname="com.glance.dashboard.tests.VerifyAddEngagement"/>
  <testcase name="GL_Settings_AE_12" time="1.527" classname="com.glance.dashboard.tests.VerifyAddEngagement">
    <failure type="java.lang.AssertionError" message="expected [[Ljava.lang.String;@35b7fa17] but found [Dashboard Management]">
      <![CDATA[java.lang.AssertionError: expected [[Ljava.lang.String;@35b7fa17] but found [Dashboard Management]
=======
<testsuite hostname="CMDMITTRN9" name="Default test" tests="7" failures="1" timestamp="8 Dec 2016 11:17:18 GMT" time="24.902" errors="0">
  <testcase name="GL_Settings_AE_09" time="1.766" classname="com.glance.dashboard.tests.VerifyAddEngagement"/>
  <testcase name="GL_Settings_AE_10" time="5.579" classname="com.glance.dashboard.tests.VerifyAddEngagement"/>
  <testcase name="GL_Settings_AE_11" time="2.572" classname="com.glance.dashboard.tests.VerifyAddEngagement"/>
  <testcase name="GL_Settings_AE_12" time="1.38" classname="com.glance.dashboard.tests.VerifyAddEngagement">
    <failure type="java.lang.AssertionError" message="expected [[Ljava.lang.String;@73eb8dd7] but found [Dashboard Management]">
      <![CDATA[java.lang.AssertionError: expected [[Ljava.lang.String;@73eb8dd7] but found [Dashboard Management]
>>>>>>> sachiniTEST
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertArrayEquals(Assert.java:169)
	at org.testng.Assert.assertEquals(Assert.java:113)
	at org.testng.Assert.assertEquals(Assert.java:179)
<<<<<<< HEAD
	at com.glance.dashboard.tests.VerifyAddEngagement.GL_Settings_AE_12(VerifyAddEngagement.java:148)
=======
<testsuite hostname="CMDMITTRN1" name="Default test" tests="5" failures="2" timestamp="8 Dec 2016 09:20:54 GMT" time="160.473" errors="0">
  <testcase name="GL_Settings_DU_41" time="1.563" classname="com.glance.datamanagement.tests.VerifyDataUploadPage"/>
  <testcase name="GL_Settings_DU_42_2" time="0.663" classname="com.glance.datamanagement.tests.VerifyDataUploadPage"/>
  <testcase name="GL_Settings_DU_42_3" time="4.526" classname="com.glance.datamanagement.tests.VerifyDataUploadPage">
    <failure type="junit.framework.AssertionFailedError">
      <![CDATA[junit.framework.AssertionFailedError
	at junit.framework.Assert.fail(Assert.java:47)
	at junit.framework.Assert.assertTrue(Assert.java:20)
	at junit.framework.Assert.assertTrue(Assert.java:27)
	at com.glance.datamanagement.tests.VerifyDataUploadPage.GL_Settings_DU_42_3(VerifyDataUploadPage.java:143)
>>>>>>> poornimaTEST
=======
	at com.glance.dashboard.tests.VerifyAddEngagement.GL_Settings_AE_12(VerifyAddEngagement.java:145)
>>>>>>> sachiniTEST
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:100)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:646)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:811)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1137)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:753)
	at org.testng.TestRunner.run(TestRunner.java:607)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:368)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:363)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:321)
	at org.testng.SuiteRunner.run(SuiteRunner.java:270)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1284)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1209)
	at org.testng.TestNG.runSuites(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1096)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </failure>
<<<<<<< HEAD
  </testcase> <!-- GL_Settings_AE_12 -->
<<<<<<< HEAD
  <testcase name="GL_Settings_AE_11_verify1" time="1.383" classname="com.glance.dashboard.tests.VerifyAddEngagement">
=======
<testsuite hostname="CMDMITTRN11" name="Default test" tests="13" failures="1" timestamp="8 Dec 2016 11:53:16 GMT" time="391.745" errors="0">
  <testcase name="GL_Main_22" time="8.733" classname="com.glance.commonPage.tests.VerifyCommonPageTopPane"/>
  <testcase name="GL_Main_23" time="32.376" classname="com.glance.commonPage.tests.VerifyCommonPageTopPane"/>
  <testcase name="GL_Main_24" time="31.639" classname="com.glance.commonPage.tests.VerifyCommonPageTopPane"/>
  <testcase name="GL_Main_25" time="36.848" classname="com.glance.commonPage.tests.VerifyCommonPageTopPane"/>
  <testcase name="GL_Main_26" time="31.778" classname="com.glance.commonPage.tests.VerifyCommonPageTopPane"/>
  <testcase name="GL_Main_27" time="6.245" classname="com.glance.commonPage.tests.VerifyCommonPageTopPane"/>
  <testcase name="GL_Main_28" time="34.317" classname="com.glance.commonPage.tests.VerifyCommonPageTopPane"/>
  <testcase name="GL_Main_29" time="34.352" classname="com.glance.commonPage.tests.VerifyCommonPageTopPane"/>
  <testcase name="GL_Main_30" time="34.323" classname="com.glance.commonPage.tests.VerifyCommonPageTopPane"/>
  <testcase name="GL_Main_31" time="34.702" classname="com.glance.commonPage.tests.VerifyCommonPageTopPane"/>
  <testcase name="GL_Main_32" time="34.582" classname="com.glance.commonPage.tests.VerifyCommonPageTopPane"/>
  <testcase name="GL_Main_33" time="34.27" classname="com.glance.commonPage.tests.VerifyCommonPageTopPane">
>>>>>>> shamamaTEST
>>>>>>> 63ec7fccdb40aed3ba4f691963db98fc59345963
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
<<<<<<< HEAD
	at com.glance.usermanagement.tests.ManageUser.GL_UM_09_1(ManageUser.java:69)
=======
<<<<<<< HEAD
	at com.glance.dashboard.tests.VerifyAddEngagement.GL_Settings_AE_11_verify1(VerifyAddEngagement.java:180)
=======
  </testcase> <!-- GL_Settings_DU_42_3 -->
  <testcase name="GL_Settings_DU_42_4" time="10.188" classname="com.glance.datamanagement.tests.VerifyDataUploadPage">
    <failure type="junit.framework.AssertionFailedError">
      <![CDATA[junit.framework.AssertionFailedError
	at junit.framework.Assert.fail(Assert.java:47)
	at junit.framework.Assert.assertTrue(Assert.java:20)
	at junit.framework.Assert.assertTrue(Assert.java:27)
	at com.glance.datamanagement.tests.VerifyDataUploadPage.GL_Settings_DU_42_4(VerifyDataUploadPage.java:162)
>>>>>>> poornimaTEST
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:100)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:646)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:811)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1137)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:753)
	at org.testng.TestRunner.run(TestRunner.java:607)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:368)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:363)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:321)
	at org.testng.SuiteRunner.run(SuiteRunner.java:270)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1284)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1209)
	at org.testng.TestNG.runSuites(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1096)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </failure>
<<<<<<< HEAD
  </testcase> <!-- GL_Settings_AE_11_verify1 -->
  <testcase name="GL_Settings_AE_11_verify2" time="21.062" classname="com.glance.dashboard.tests.VerifyAddEngagement">
    <failure type="org.openqa.selenium.WebDriverException" message="chrome not reachable
  (Session info: chrome=54.0.2840.99)
  (Driver info: chromedriver=2.25.426923 (0390b88869384d6eb0d5d09729679f934aab9eed),platform=Windows NT 6.1.7601 SP1 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 7.03 seconds
Build info: version: &amp;apos;2.53.1&amp;apos;, revision: &amp;apos;a36b8b1cd5757287168e54b817830adce9b0158d&amp;apos;, time: &amp;apos;2016-06-30 19:26:09&amp;apos;
System info: host: &amp;apos;CMDMITTRN9&amp;apos;, ip: &amp;apos;172.28.32.101&amp;apos;, os.name: &amp;apos;Windows 7&amp;apos;, os.arch: &amp;apos;amd64&amp;apos;, os.version: &amp;apos;6.1&amp;apos;, java.version: &amp;apos;1.7.0_67&amp;apos;
*** Element info: {Using=xpath, value=//div[@class=&amp;apos;x_title&amp;apos;]/h2}
Session ID: 28e240d28734ff0e6029fec76ab7e779
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities [{platform=XP, acceptSslCerts=true, javascriptEnabled=true, browserName=chrome, chrome={userDataDir=C:\Users\SDSMAD~1\AppData\Local\Temp\scoped_dir440_19963, chromedriverVersion=2.25.426923 (0390b88869384d6eb0d5d09729679f934aab9eed)}, networkConnectionEnabled=false, rotatable=false, locationContextEnabled=true, mobileEmulationEnabled=false, version=54.0.2840.99, pageLoadStrategy=normal, takesHeapSnapshot=true, cssSelectorsEnabled=true, databaseEnabled=false, handlesAlerts=true, browserConnectionEnabled=false, webStorageEnabled=true, nativeEvents=true, hasTouchScreen=false, applicationCacheEnabled=false, takesScreenshot=true}]">
      <![CDATA[org.openqa.selenium.WebDriverException: chrome not reachable
  (Session info: chrome=54.0.2840.99)
  (Driver info: chromedriver=2.25.426923 (0390b88869384d6eb0d5d09729679f934aab9eed),platform=Windows NT 6.1.7601 SP1 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 7.03 seconds
Build info: version: '2.53.1', revision: 'a36b8b1cd5757287168e54b817830adce9b0158d', time: '2016-06-30 19:26:09'
System info: host: 'CMDMITTRN9', ip: '172.28.32.101', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.7.0_67'
*** Element info: {Using=xpath, value=//div[@class='x_title']/h2}
Session ID: 28e240d28734ff0e6029fec76ab7e779
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities [{platform=XP, acceptSslCerts=true, javascriptEnabled=true, browserName=chrome, chrome={userDataDir=C:\Users\SDSMAD~1\AppData\Local\Temp\scoped_dir440_19963, chromedriverVersion=2.25.426923 (0390b88869384d6eb0d5d09729679f934aab9eed)}, networkConnectionEnabled=false, rotatable=false, locationContextEnabled=true, mobileEmulationEnabled=false, version=54.0.2840.99, pageLoadStrategy=normal, takesHeapSnapshot=true, cssSelectorsEnabled=true, databaseEnabled=false, handlesAlerts=true, browserConnectionEnabled=false, webStorageEnabled=true, nativeEvents=true, hasTouchScreen=false, applicationCacheEnabled=false, takesScreenshot=true}]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:206)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:158)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:678)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:363)
	at org.openqa.selenium.remote.RemoteWebDriver.findElementByXPath(RemoteWebDriver.java:500)
	at org.openqa.selenium.By$ByXPath.findElement(By.java:361)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:355)
	at org.openqa.selenium.support.pagefactory.DefaultElementLocator.findElement(DefaultElementLocator.java:69)
	at org.openqa.selenium.support.pagefactory.internal.LocatingElementHandler.invoke(LocatingElementHandler.java:38)
	at com.sun.proxy.$Proxy12.getText(Unknown Source)
	at com.glance.pageobjects.dashboard.AddEngagementPage.getPageName(AddEngagementPage.java:86)
	at com.glance.dashboard.tests.VerifyAddEngagement.GL_Settings_AE_11_verify2(VerifyAddEngagement.java:207)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:100)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:646)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:811)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1137)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:753)
	at org.testng.TestRunner.run(TestRunner.java:607)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:368)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:363)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:321)
	at org.testng.SuiteRunner.run(SuiteRunner.java:270)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1284)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1209)
	at org.testng.TestNG.runSuites(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1096)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </failure>
  </testcase> <!-- GL_Settings_AE_11_verify2 -->
  <testcase name="GL_Settings_AE_13" time="21.091" classname="com.glance.dashboard.tests.VerifyAddEngagement">
    <failure type="org.openqa.selenium.WebDriverException" message="chrome not reachable
  (Session info: chrome=54.0.2840.99)
  (Driver info: chromedriver=2.25.426923 (0390b88869384d6eb0d5d09729679f934aab9eed),platform=Windows NT 6.1.7601 SP1 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 7.02 seconds
Build info: version: &amp;apos;2.53.1&amp;apos;, revision: &amp;apos;a36b8b1cd5757287168e54b817830adce9b0158d&amp;apos;, time: &amp;apos;2016-06-30 19:26:09&amp;apos;
System info: host: &amp;apos;CMDMITTRN9&amp;apos;, ip: &amp;apos;172.28.32.101&amp;apos;, os.name: &amp;apos;Windows 7&amp;apos;, os.arch: &amp;apos;amd64&amp;apos;, os.version: &amp;apos;6.1&amp;apos;, java.version: &amp;apos;1.7.0_67&amp;apos;
Session ID: 28e240d28734ff0e6029fec76ab7e779
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities [{platform=XP, acceptSslCerts=true, javascriptEnabled=true, browserName=chrome, chrome={userDataDir=C:\Users\SDSMAD~1\AppData\Local\Temp\scoped_dir440_19963, chromedriverVersion=2.25.426923 (0390b88869384d6eb0d5d09729679f934aab9eed)}, networkConnectionEnabled=false, rotatable=false, locationContextEnabled=true, mobileEmulationEnabled=false, version=54.0.2840.99, pageLoadStrategy=normal, takesHeapSnapshot=true, cssSelectorsEnabled=true, databaseEnabled=false, handlesAlerts=true, browserConnectionEnabled=false, webStorageEnabled=true, nativeEvents=true, hasTouchScreen=false, applicationCacheEnabled=false, takesScreenshot=true}]">
      <![CDATA[org.openqa.selenium.WebDriverException: chrome not reachable
  (Session info: chrome=54.0.2840.99)
  (Driver info: chromedriver=2.25.426923 (0390b88869384d6eb0d5d09729679f934aab9eed),platform=Windows NT 6.1.7601 SP1 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 7.02 seconds
Build info: version: '2.53.1', revision: 'a36b8b1cd5757287168e54b817830adce9b0158d', time: '2016-06-30 19:26:09'
System info: host: 'CMDMITTRN9', ip: '172.28.32.101', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.7.0_67'
Session ID: 28e240d28734ff0e6029fec76ab7e779
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities [{platform=XP, acceptSslCerts=true, javascriptEnabled=true, browserName=chrome, chrome={userDataDir=C:\Users\SDSMAD~1\AppData\Local\Temp\scoped_dir440_19963, chromedriverVersion=2.25.426923 (0390b88869384d6eb0d5d09729679f934aab9eed)}, networkConnectionEnabled=false, rotatable=false, locationContextEnabled=true, mobileEmulationEnabled=false, version=54.0.2840.99, pageLoadStrategy=normal, takesHeapSnapshot=true, cssSelectorsEnabled=true, databaseEnabled=false, handlesAlerts=true, browserConnectionEnabled=false, webStorageEnabled=true, nativeEvents=true, hasTouchScreen=false, applicationCacheEnabled=false, takesScreenshot=true}]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:206)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:158)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:678)
	at org.openqa.selenium.remote.RemoteWebDriver.executeScript(RemoteWebDriver.java:577)
	at com.glance.pageobjects.common.CommonPageObject$1.apply(CommonPageObject.java:602)
	at com.glance.pageobjects.common.CommonPageObject$1.apply(CommonPageObject.java:1)
	at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:238)
	at com.glance.pageobjects.common.CommonPageObject.waitForPageLoad(CommonPageObject.java:600)
	at com.glance.dashboard.tests.VerifyAddEngagement.GL_Settings_AE_13(VerifyAddEngagement.java:241)
>>>>>>> sachiniTEST
>>>>>>> 63ec7fccdb40aed3ba4f691963db98fc59345963
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:100)
<<<<<<< HEAD
=======
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:515)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:216)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:590)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:811)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1137)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:753)
	at org.testng.TestRunner.run(TestRunner.java:607)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:368)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:363)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:321)
	at org.testng.SuiteRunner.run(SuiteRunner.java:270)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1284)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1209)
	at org.testng.TestNG.runSuites(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1096)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </failure>
<<<<<<< HEAD
  </testcase> <!-- @BeforeMethod verifyGoToDeleteUserPage -->
  <testcase name="@BeforeMethod verifyGoToDeleteUserPage" time="0.0" classname="com.glance.usermanagement.tests.TestDeleteUser">
    <skipped/>
  </testcase> <!-- @BeforeMethod verifyGoToDeleteUserPage -->
  <testcase name="@BeforeMethod verifyGoToDeleteUserPage" time="0.0" classname="com.glance.usermanagement.tests.TestDeleteUser">
    <skipped/>
  </testcase> <!-- @BeforeMethod verifyGoToDeleteUserPage -->
  <testcase name="GL_Settings_MU_62_verifyGoBack" time="0.0" classname="com.glance.usermanagement.tests.TestDeleteUser">
    <skipped/>
  </testcase> <!-- GL_Settings_MU_62_verifyGoBack -->
  <testcase name="GL_Settings_MU_61_verifyCancelDeleteUser" time="0.002" classname="com.glance.usermanagement.tests.TestDeleteUser">
    <skipped/>
  </testcase> <!-- GL_Settings_MU_61_verifyCancelDeleteUser -->
  <testcase name="GL_Settings_MU_60_verifyDeleteUser" time="0.0" classname="com.glance.usermanagement.tests.TestDeleteUser">
    <skipped/>
  </testcase> <!-- GL_Settings_MU_60_verifyDeleteUser -->
=======
<testsuite hostname="CMDMITTRN7" name="Default test" tests="1" failures="0" timestamp="8 Dec 2016 07:39:45 GMT" time="269.807" errors="0">
  <testcase name="GL_Settings_07" time="256.88" classname="userlogin.VerifyProfileUpdatePage"/>
>>>>>>> neelamaniTest
=======
  </testcase> <!-- GL_Settings_AE_13 -->
>>>>>>> sachiniTEST
=======
<testsuite hostname="CMDMITTRN2" name="Default test" tests="7" failures="0" timestamp="8 Dec 2016 10:21:28 GMT" time="768.06" errors="0">
  <testcase name="GL_Settings_GM_69_verifyAddGroupMembership" time="27.368" classname="com.glance.usermanagement.tests.TestGroupMembership"/>
  <testcase name="GL_Settings_GM_71_verifyAddDuplicateEntries" time="8.753" classname="com.glance.usermanagement.tests.TestGroupMembership"/>
  <testcase name="GL_Settings_GM_70_verifyAddGroupMembershipWithEmptyFields" time="11.057" classname="com.glance.usermanagement.tests.TestGroupMembership"/>
  <testcase name="verifyCancelAddGroupMembership" time="0.332" classname="com.glance.usermanagement.tests.TestGroupMembership"/>
  <testcase name="GL_Settings_GM_72_viewMembers" time="0.481" classname="com.glance.usermanagement.tests.TestGroupMembership"/>
  <testcase name="GL_Settings_GM_74_verifyCancelDelete" time="15.504" classname="com.glance.usermanagement.tests.TestGroupMembership"/>
  <testcase name="GL_Settings_GM_73_verifyDeleteGroupMembership" time="15.618" classname="com.glance.usermanagement.tests.TestGroupMembership"/>
>>>>>>> sajeththaTest
=======
  </testcase> <!-- GL_Settings_DU_42_4 -->
  <testcase name="GL_Settings_DU_44" time="20.163" classname="com.glance.datamanagement.tests.VerifyDataUploadPage"/>
>>>>>>> poornimaTEST
=======
  <testcase name="GL_Settings_AE_11_verify1" time="1.814" classname="com.glance.dashboard.tests.VerifyAddEngagement"/>
  <testcase name="GL_Settings_AE_11_verify2" time="2.077" classname="com.glance.dashboard.tests.VerifyAddEngagement"/>
  <testcase name="GL_Settings_AE_13" time="0.785" classname="com.glance.dashboard.tests.VerifyAddEngagement"/>
>>>>>>> sachiniTEST
=======
	at com.glance.commonPage.tests.VerifyCommonPageTopPane.GL_Main_33(VerifyCommonPageTopPane.java:267)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:100)
>>>>>>> 63ec7fccdb40aed3ba4f691963db98fc59345963
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:646)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:811)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1129)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:746)
	at org.testng.TestRunner.run(TestRunner.java:600)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1264)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1189)
	at org.testng.TestNG.runSuites(TestNG.java:1104)
	at org.testng.TestNG.run(TestNG.java:1076)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:152)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:57)
]]>
    </failure>
<<<<<<< HEAD
  </testcase> <!-- GL_UM_09_1 -->
=======
  </testcase> <!-- GL_Main_33 -->
  <testcase name="GL_Main_34" time="34.235" classname="com.glance.commonPage.tests.VerifyCommonPageTopPane"/>
>>>>>>> shamamaTEST
>>>>>>> 63ec7fccdb40aed3ba4f691963db98fc59345963
</testsuite> <!-- Default test -->
