<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="12" total="24" passed="12">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="82723" started-at="2016-12-12T16:38:43Z" finished-at="2016-12-12T16:40:06Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="82723" started-at="2016-12-12T16:38:43Z" finished-at="2016-12-12T16:40:06Z">
      <class name="com.glance.usermanagement.tests.ManageUser">
        <test-method status="PASS" signature="testStartUp()[pri:0, instance:com.glance.usermanagement.tests.ManageUser@4dfa3a9d]" name="testStartUp" is-config="true" duration-ms="207" started-at="2016-12-12T22:08:43Z" finished-at="2016-12-12T22:08:43Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testStartUp -->
        <test-method status="PASS" signature="initializeTest()[pri:0, instance:com.glance.usermanagement.tests.ManageUser@4dfa3a9d]" name="initializeTest" is-config="true" duration-ms="4610" started-at="2016-12-12T22:08:43Z" finished-at="2016-12-12T22:08:48Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initializeTest -->
        <test-method status="PASS" signature="systemLogin()[pri:0, instance:com.glance.usermanagement.tests.ManageUser@4dfa3a9d]" name="systemLogin" is-config="true" duration-ms="2178" started-at="2016-12-12T22:08:49Z" finished-at="2016-12-12T22:08:51Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- systemLogin -->
        <test-method status="PASS" signature="GL_UM_02(java.lang.String)[pri:1, instance:com.glance.usermanagement.tests.ManageUser@4dfa3a9d]" name="GL_UM_02" duration-ms="441" started-at="2016-12-12T22:08:51Z" data-provider="GL_UM_02" finished-at="2016-12-12T22:08:51Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[User ID]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- GL_UM_02 -->
        <test-method status="PASS" signature="systemLogOut()[pri:0, instance:com.glance.usermanagement.tests.ManageUser@4dfa3a9d]" name="systemLogOut" is-config="true" duration-ms="134" started-at="2016-12-12T22:08:51Z" finished-at="2016-12-12T22:08:51Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- systemLogOut -->
        <test-method status="PASS" signature="systemLogin()[pri:0, instance:com.glance.usermanagement.tests.ManageUser@4dfa3a9d]" name="systemLogin" is-config="true" duration-ms="1147" started-at="2016-12-12T22:08:51Z" finished-at="2016-12-12T22:08:53Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- systemLogin -->
        <test-method status="PASS" signature="GL_UM_02(java.lang.String)[pri:1, instance:com.glance.usermanagement.tests.ManageUser@4dfa3a9d]" name="GL_UM_02" duration-ms="375" started-at="2016-12-12T22:08:53Z" data-provider="GL_UM_02" finished-at="2016-12-12T22:08:53Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[User Name]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- GL_UM_02 -->
        <test-method status="PASS" signature="systemLogOut()[pri:0, instance:com.glance.usermanagement.tests.ManageUser@4dfa3a9d]" name="systemLogOut" is-config="true" duration-ms="47" started-at="2016-12-12T22:08:53Z" finished-at="2016-12-12T22:08:53Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- systemLogOut -->
        <test-method status="PASS" signature="systemLogin()[pri:0, instance:com.glance.usermanagement.tests.ManageUser@4dfa3a9d]" name="systemLogin" is-config="true" duration-ms="1116" started-at="2016-12-12T22:08:53Z" finished-at="2016-12-12T22:08:54Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- systemLogin -->
        <test-method status="PASS" signature="GL_UM_02(java.lang.String)[pri:1, instance:com.glance.usermanagement.tests.ManageUser@4dfa3a9d]" name="GL_UM_02" duration-ms="377" started-at="2016-12-12T22:08:54Z" data-provider="GL_UM_02" finished-at="2016-12-12T22:08:54Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[First Name]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- GL_UM_02 -->
        <test-method status="PASS" signature="systemLogOut()[pri:0, instance:com.glance.usermanagement.tests.ManageUser@4dfa3a9d]" name="systemLogOut" is-config="true" duration-ms="56" started-at="2016-12-12T22:08:54Z" finished-at="2016-12-12T22:08:54Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- systemLogOut -->
        <test-method status="PASS" signature="systemLogin()[pri:0, instance:com.glance.usermanagement.tests.ManageUser@4dfa3a9d]" name="systemLogin" is-config="true" duration-ms="1370" started-at="2016-12-12T22:08:54Z" finished-at="2016-12-12T22:08:56Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- systemLogin -->
        <test-method status="PASS" signature="GL_UM_02(java.lang.String)[pri:1, instance:com.glance.usermanagement.tests.ManageUser@4dfa3a9d]" name="GL_UM_02" duration-ms="357" started-at="2016-12-12T22:08:56Z" data-provider="GL_UM_02" finished-at="2016-12-12T22:08:56Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[Last Name]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- GL_UM_02 -->
        <test-method status="PASS" signature="systemLogOut()[pri:0, instance:com.glance.usermanagement.tests.ManageUser@4dfa3a9d]" name="systemLogOut" is-config="true" duration-ms="120" started-at="2016-12-12T22:08:56Z" finished-at="2016-12-12T22:08:56Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- systemLogOut -->
        <test-method status="PASS" signature="systemLogin()[pri:0, instance:com.glance.usermanagement.tests.ManageUser@4dfa3a9d]" name="systemLogin" is-config="true" duration-ms="1031" started-at="2016-12-12T22:08:56Z" finished-at="2016-12-12T22:08:57Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- systemLogin -->
        <test-method status="PASS" signature="GL_UM_02(java.lang.String)[pri:1, instance:com.glance.usermanagement.tests.ManageUser@4dfa3a9d]" name="GL_UM_02" duration-ms="367" started-at="2016-12-12T22:08:57Z" data-provider="GL_UM_02" finished-at="2016-12-12T22:08:58Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[Job Role]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- GL_UM_02 -->
        <test-method status="PASS" signature="systemLogOut()[pri:0, instance:com.glance.usermanagement.tests.ManageUser@4dfa3a9d]" name="systemLogOut" is-config="true" duration-ms="115" started-at="2016-12-12T22:08:58Z" finished-at="2016-12-12T22:08:58Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- systemLogOut -->
        <test-method status="PASS" signature="systemLogin()[pri:0, instance:com.glance.usermanagement.tests.ManageUser@4dfa3a9d]" name="systemLogin" is-config="true" duration-ms="928" started-at="2016-12-12T22:08:58Z" finished-at="2016-12-12T22:08:59Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- systemLogin -->
        <test-method status="FAIL" signature="GL_UM_08(java.lang.String, int)[pri:2, instance:com.glance.usermanagement.tests.ManageUser@4dfa3a9d]" name="GL_UM_08" duration-ms="154" started-at="2016-12-12T22:08:59Z" data-provider="GL_UM_08" finished-at="2016-12-12T22:08:59Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[Admin]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[0]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [0] but found [3]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [0] but found [3]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:389)
	at org.testng.Assert.assertEquals(Assert.java:399)
	at com.glance.usermanagement.tests.ManageUser.GL_UM_08(ManageUser.java:55)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:100)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:646)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:811)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1129)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:746)
	at org.testng.TestRunner.run(TestRunner.java:600)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1264)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1189)
	at org.testng.TestNG.runSuites(TestNG.java:1104)
	at org.testng.TestNG.run(TestNG.java:1076)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:152)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:57)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- GL_UM_08 -->
        <test-method status="PASS" signature="systemLogOut()[pri:0, instance:com.glance.usermanagement.tests.ManageUser@4dfa3a9d]" name="systemLogOut" is-config="true" duration-ms="120" started-at="2016-12-12T22:08:59Z" finished-at="2016-12-12T22:08:59Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- systemLogOut -->
        <test-method status="PASS" signature="systemLogin()[pri:0, instance:com.glance.usermanagement.tests.ManageUser@4dfa3a9d]" name="systemLogin" is-config="true" duration-ms="1049" started-at="2016-12-12T22:08:59Z" finished-at="2016-12-12T22:09:00Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- systemLogin -->
        <test-method status="FAIL" signature="GL_UM_08(java.lang.String, int)[pri:2, instance:com.glance.usermanagement.tests.ManageUser@4dfa3a9d]" name="GL_UM_08" duration-ms="103" started-at="2016-12-12T22:09:00Z" data-provider="GL_UM_08" finished-at="2016-12-12T22:09:00Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[Oshadha]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[0]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [0] but found [2]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [0] but found [2]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:389)
	at org.testng.Assert.assertEquals(Assert.java:399)
	at com.glance.usermanagement.tests.ManageUser.GL_UM_08(ManageUser.java:55)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:100)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:646)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:811)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1129)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:746)
	at org.testng.TestRunner.run(TestRunner.java:600)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1264)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1189)
	at org.testng.TestNG.runSuites(TestNG.java:1104)
	at org.testng.TestNG.run(TestNG.java:1076)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:152)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:57)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- GL_UM_08 -->
        <test-method status="PASS" signature="systemLogOut()[pri:0, instance:com.glance.usermanagement.tests.ManageUser@4dfa3a9d]" name="systemLogOut" is-config="true" duration-ms="128" started-at="2016-12-12T22:09:00Z" finished-at="2016-12-12T22:09:00Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- systemLogOut -->
        <test-method status="PASS" signature="systemLogin()[pri:0, instance:com.glance.usermanagement.tests.ManageUser@4dfa3a9d]" name="systemLogin" is-config="true" duration-ms="996" started-at="2016-12-12T22:09:00Z" finished-at="2016-12-12T22:09:01Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- systemLogin -->
        <test-method status="FAIL" signature="GL_UM_08(java.lang.String, int)[pri:2, instance:com.glance.usermanagement.tests.ManageUser@4dfa3a9d]" name="GL_UM_08" duration-ms="81" started-at="2016-12-12T22:09:01Z" data-provider="GL_UM_08" finished-at="2016-12-12T22:09:01Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[as]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[0]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [0] but found [9]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [0] but found [9]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:389)
	at org.testng.Assert.assertEquals(Assert.java:399)
	at com.glance.usermanagement.tests.ManageUser.GL_UM_08(ManageUser.java:55)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:100)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:646)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:811)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1129)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:746)
	at org.testng.TestRunner.run(TestRunner.java:600)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1264)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1189)
	at org.testng.TestNG.runSuites(TestNG.java:1104)
	at org.testng.TestNG.run(TestNG.java:1076)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:152)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:57)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- GL_UM_08 -->
        <test-method status="PASS" signature="systemLogOut()[pri:0, instance:com.glance.usermanagement.tests.ManageUser@4dfa3a9d]" name="systemLogOut" is-config="true" duration-ms="132" started-at="2016-12-12T22:09:01Z" finished-at="2016-12-12T22:09:02Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- systemLogOut -->
        <test-method status="PASS" signature="systemLogin()[pri:0, instance:com.glance.usermanagement.tests.ManageUser@4dfa3a9d]" name="systemLogin" is-config="true" duration-ms="973" started-at="2016-12-12T22:09:02Z" finished-at="2016-12-12T22:09:03Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- systemLogin -->
        <test-method status="FAIL" signature="GL_UM_08(java.lang.String, int)[pri:2, instance:com.glance.usermanagement.tests.ManageUser@4dfa3a9d]" name="GL_UM_08" duration-ms="93" started-at="2016-12-12T22:09:03Z" data-provider="GL_UM_08" finished-at="2016-12-12T22:09:03Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[test]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[0]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [0] but found [6]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [0] but found [6]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:389)
	at org.testng.Assert.assertEquals(Assert.java:399)
	at com.glance.usermanagement.tests.ManageUser.GL_UM_08(ManageUser.java:55)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:100)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:646)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:811)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1129)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:746)
	at org.testng.TestRunner.run(TestRunner.java:600)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1264)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1189)
	at org.testng.TestNG.runSuites(TestNG.java:1104)
	at org.testng.TestNG.run(TestNG.java:1076)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:152)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:57)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- GL_UM_08 -->
        <test-method status="PASS" signature="systemLogOut()[pri:0, instance:com.glance.usermanagement.tests.ManageUser@4dfa3a9d]" name="systemLogOut" is-config="true" duration-ms="155" started-at="2016-12-12T22:09:03Z" finished-at="2016-12-12T22:09:03Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- systemLogOut -->
        <test-method status="PASS" signature="systemLogin()[pri:0, instance:com.glance.usermanagement.tests.ManageUser@4dfa3a9d]" name="systemLogin" is-config="true" duration-ms="989" started-at="2016-12-12T22:09:03Z" finished-at="2016-12-12T22:09:04Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- systemLogin -->
        <test-method status="FAIL" signature="GL_UM_08(java.lang.String, int)[pri:2, instance:com.glance.usermanagement.tests.ManageUser@4dfa3a9d]" name="GL_UM_08" duration-ms="136" started-at="2016-12-12T22:09:04Z" data-provider="GL_UM_08" finished-at="2016-12-12T22:09:04Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[Wijesooriya]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[0]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [0] but found [2]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [0] but found [2]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:389)
	at org.testng.Assert.assertEquals(Assert.java:399)
	at com.glance.usermanagement.tests.ManageUser.GL_UM_08(ManageUser.java:55)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:100)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:646)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:811)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1129)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:746)
	at org.testng.TestRunner.run(TestRunner.java:600)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1264)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1189)
	at org.testng.TestNG.runSuites(TestNG.java:1104)
	at org.testng.TestNG.run(TestNG.java:1076)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:152)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:57)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- GL_UM_08 -->
        <test-method status="PASS" signature="systemLogOut()[pri:0, instance:com.glance.usermanagement.tests.ManageUser@4dfa3a9d]" name="systemLogOut" is-config="true" duration-ms="110" started-at="2016-12-12T22:09:04Z" finished-at="2016-12-12T22:09:04Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- systemLogOut -->
        <test-method status="PASS" signature="systemLogin()[pri:0, instance:com.glance.usermanagement.tests.ManageUser@4dfa3a9d]" name="systemLogin" is-config="true" duration-ms="1013" started-at="2016-12-12T22:09:04Z" finished-at="2016-12-12T22:09:05Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- systemLogin -->
        <test-method status="FAIL" signature="GL_UM_08(java.lang.String, int)[pri:2, instance:com.glance.usermanagement.tests.ManageUser@4dfa3a9d]" name="GL_UM_08" duration-ms="81" started-at="2016-12-12T22:09:05Z" data-provider="GL_UM_08" finished-at="2016-12-12T22:09:05Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[11]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[0]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [0] but found [2]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [0] but found [2]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:389)
	at org.testng.Assert.assertEquals(Assert.java:399)
	at com.glance.usermanagement.tests.ManageUser.GL_UM_08(ManageUser.java:55)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:100)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:646)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:811)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1129)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:746)
	at org.testng.TestRunner.run(TestRunner.java:600)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1264)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1189)
	at org.testng.TestNG.runSuites(TestNG.java:1104)
	at org.testng.TestNG.run(TestNG.java:1076)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:152)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:57)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- GL_UM_08 -->
        <test-method status="PASS" signature="systemLogOut()[pri:0, instance:com.glance.usermanagement.tests.ManageUser@4dfa3a9d]" name="systemLogOut" is-config="true" duration-ms="114" started-at="2016-12-12T22:09:05Z" finished-at="2016-12-12T22:09:05Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- systemLogOut -->
        <test-method status="PASS" signature="systemLogin()[pri:0, instance:com.glance.usermanagement.tests.ManageUser@4dfa3a9d]" name="systemLogin" is-config="true" duration-ms="979" started-at="2016-12-12T22:09:05Z" finished-at="2016-12-12T22:09:06Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- systemLogin -->
        <test-method status="PASS" signature="GL_UM_09_1(java.lang.String)[pri:3, instance:com.glance.usermanagement.tests.ManageUser@4dfa3a9d]" name="GL_UM_09_1" duration-ms="517" started-at="2016-12-12T22:09:06Z" data-provider="GL_UM_09_1" finished-at="2016-12-12T22:09:07Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[First]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- GL_UM_09_1 -->
        <test-method status="PASS" signature="systemLogOut()[pri:0, instance:com.glance.usermanagement.tests.ManageUser@4dfa3a9d]" name="systemLogOut" is-config="true" duration-ms="50" started-at="2016-12-12T22:09:07Z" finished-at="2016-12-12T22:09:07Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- systemLogOut -->
        <test-method status="PASS" signature="systemLogin()[pri:0, instance:com.glance.usermanagement.tests.ManageUser@4dfa3a9d]" name="systemLogin" is-config="true" duration-ms="1029" started-at="2016-12-12T22:09:07Z" finished-at="2016-12-12T22:09:08Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- systemLogin -->
        <test-method status="PASS" signature="GL_UM_09_1(java.lang.String)[pri:3, instance:com.glance.usermanagement.tests.ManageUser@4dfa3a9d]" name="GL_UM_09_1" duration-ms="568" started-at="2016-12-12T22:09:08Z" data-provider="GL_UM_09_1" finished-at="2016-12-12T22:09:08Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[Next]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- GL_UM_09_1 -->
        <test-method status="PASS" signature="systemLogOut()[pri:0, instance:com.glance.usermanagement.tests.ManageUser@4dfa3a9d]" name="systemLogOut" is-config="true" duration-ms="125" started-at="2016-12-12T22:09:08Z" finished-at="2016-12-12T22:09:09Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- systemLogOut -->
        <test-method status="PASS" signature="systemLogin()[pri:0, instance:com.glance.usermanagement.tests.ManageUser@4dfa3a9d]" name="systemLogin" is-config="true" duration-ms="1012" started-at="2016-12-12T22:09:09Z" finished-at="2016-12-12T22:09:10Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- systemLogin -->
        <test-method status="PASS" signature="GL_UM_09_1(java.lang.String)[pri:3, instance:com.glance.usermanagement.tests.ManageUser@4dfa3a9d]" name="GL_UM_09_1" duration-ms="576" started-at="2016-12-12T22:09:10Z" data-provider="GL_UM_09_1" finished-at="2016-12-12T22:09:10Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[Last]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- GL_UM_09_1 -->
        <test-method status="PASS" signature="systemLogOut()[pri:0, instance:com.glance.usermanagement.tests.ManageUser@4dfa3a9d]" name="systemLogOut" is-config="true" duration-ms="146" started-at="2016-12-12T22:09:10Z" finished-at="2016-12-12T22:09:10Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- systemLogOut -->
        <test-method status="PASS" signature="systemLogin()[pri:0, instance:com.glance.usermanagement.tests.ManageUser@4dfa3a9d]" name="systemLogin" is-config="true" duration-ms="997" started-at="2016-12-12T22:09:10Z" finished-at="2016-12-12T22:09:11Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- systemLogin -->
        <test-method status="PASS" signature="GL_UM_09_1(java.lang.String)[pri:3, instance:com.glance.usermanagement.tests.ManageUser@4dfa3a9d]" name="GL_UM_09_1" duration-ms="470" started-at="2016-12-12T22:09:11Z" data-provider="GL_UM_09_1" finished-at="2016-12-12T22:09:12Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[Previous]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- GL_UM_09_1 -->
        <test-method status="PASS" signature="systemLogOut()[pri:0, instance:com.glance.usermanagement.tests.ManageUser@4dfa3a9d]" name="systemLogOut" is-config="true" duration-ms="52" started-at="2016-12-12T22:09:12Z" finished-at="2016-12-12T22:09:12Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- systemLogOut -->
        <test-method status="PASS" signature="systemLogin()[pri:0, instance:com.glance.usermanagement.tests.ManageUser@4dfa3a9d]" name="systemLogin" is-config="true" duration-ms="1115" started-at="2016-12-12T22:09:12Z" finished-at="2016-12-12T22:09:13Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- systemLogin -->
        <test-method status="FAIL" signature="GL_UM_09_2(int)[pri:4, instance:com.glance.usermanagement.tests.ManageUser@4dfa3a9d]" name="GL_UM_09_2" duration-ms="10287" started-at="2016-12-12T22:09:13Z" data-provider="GL_UM_09_2" finished-at="2016-12-12T22:09:23Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[1]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at com.glance.usermanagement.tests.ManageUser.GL_UM_09_2(ManageUser.java:81)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:100)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:646)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:811)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1129)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:746)
	at org.testng.TestRunner.run(TestRunner.java:600)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1264)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1189)
	at org.testng.TestNG.runSuites(TestNG.java:1104)
	at org.testng.TestNG.run(TestNG.java:1076)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:152)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:57)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- GL_UM_09_2 -->
        <test-method status="PASS" signature="systemLogOut()[pri:0, instance:com.glance.usermanagement.tests.ManageUser@4dfa3a9d]" name="systemLogOut" is-config="true" duration-ms="244" started-at="2016-12-12T22:09:23Z" finished-at="2016-12-12T22:09:24Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- systemLogOut -->
        <test-method status="PASS" signature="systemLogin()[pri:0, instance:com.glance.usermanagement.tests.ManageUser@4dfa3a9d]" name="systemLogin" is-config="true" duration-ms="930" started-at="2016-12-12T22:09:24Z" finished-at="2016-12-12T22:09:25Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- systemLogin -->
        <test-method status="FAIL" signature="GL_UM_09_2(int)[pri:4, instance:com.glance.usermanagement.tests.ManageUser@4dfa3a9d]" name="GL_UM_09_2" duration-ms="10399" started-at="2016-12-12T22:09:25Z" data-provider="GL_UM_09_2" finished-at="2016-12-12T22:09:35Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[2]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at com.glance.usermanagement.tests.ManageUser.GL_UM_09_2(ManageUser.java:81)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:100)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:646)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:811)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1129)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:746)
	at org.testng.TestRunner.run(TestRunner.java:600)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1264)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1189)
	at org.testng.TestNG.runSuites(TestNG.java:1104)
	at org.testng.TestNG.run(TestNG.java:1076)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:152)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:57)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- GL_UM_09_2 -->
        <test-method status="PASS" signature="systemLogOut()[pri:0, instance:com.glance.usermanagement.tests.ManageUser@4dfa3a9d]" name="systemLogOut" is-config="true" duration-ms="208" started-at="2016-12-12T22:09:35Z" finished-at="2016-12-12T22:09:35Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- systemLogOut -->
        <test-method status="PASS" signature="systemLogin()[pri:0, instance:com.glance.usermanagement.tests.ManageUser@4dfa3a9d]" name="systemLogin" is-config="true" duration-ms="1112" started-at="2016-12-12T22:09:35Z" finished-at="2016-12-12T22:09:36Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- systemLogin -->
        <test-method status="FAIL" signature="GL_UM_09_2(int)[pri:4, instance:com.glance.usermanagement.tests.ManageUser@4dfa3a9d]" name="GL_UM_09_2" duration-ms="10413" started-at="2016-12-12T22:09:36Z" data-provider="GL_UM_09_2" finished-at="2016-12-12T22:09:47Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[3]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at com.glance.usermanagement.tests.ManageUser.GL_UM_09_2(ManageUser.java:81)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:100)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:646)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:811)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1129)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:746)
	at org.testng.TestRunner.run(TestRunner.java:600)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1264)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1189)
	at org.testng.TestNG.runSuites(TestNG.java:1104)
	at org.testng.TestNG.run(TestNG.java:1076)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:152)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:57)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- GL_UM_09_2 -->
        <test-method status="PASS" signature="systemLogOut()[pri:0, instance:com.glance.usermanagement.tests.ManageUser@4dfa3a9d]" name="systemLogOut" is-config="true" duration-ms="169" started-at="2016-12-12T22:09:47Z" finished-at="2016-12-12T22:09:47Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- systemLogOut -->
        <test-method status="PASS" signature="systemLogin()[pri:0, instance:com.glance.usermanagement.tests.ManageUser@4dfa3a9d]" name="systemLogin" is-config="true" duration-ms="1057" started-at="2016-12-12T22:09:47Z" finished-at="2016-12-12T22:09:48Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- systemLogin -->
        <test-method status="PASS" signature="GL_UM_10()[pri:5, instance:com.glance.usermanagement.tests.ManageUser@4dfa3a9d]" name="GL_UM_10" duration-ms="10197" started-at="2016-12-12T22:09:48Z" finished-at="2016-12-12T22:09:58Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- GL_UM_10 -->
        <test-method status="PASS" signature="systemLogOut()[pri:0, instance:com.glance.usermanagement.tests.ManageUser@4dfa3a9d]" name="systemLogOut" is-config="true" duration-ms="156" started-at="2016-12-12T22:09:58Z" finished-at="2016-12-12T22:09:58Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- systemLogOut -->
        <test-method status="PASS" signature="systemLogin()[pri:0, instance:com.glance.usermanagement.tests.ManageUser@4dfa3a9d]" name="systemLogin" is-config="true" duration-ms="948" started-at="2016-12-12T22:09:58Z" finished-at="2016-12-12T22:09:59Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- systemLogin -->
        <test-method status="PASS" signature="GL_UM_11()[pri:6, instance:com.glance.usermanagement.tests.ManageUser@4dfa3a9d]" name="GL_UM_11" duration-ms="200" started-at="2016-12-12T22:09:59Z" finished-at="2016-12-12T22:09:59Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- GL_UM_11 -->
        <test-method status="PASS" signature="systemLogOut()[pri:0, instance:com.glance.usermanagement.tests.ManageUser@4dfa3a9d]" name="systemLogOut" is-config="true" duration-ms="65" started-at="2016-12-12T22:09:59Z" finished-at="2016-12-12T22:09:59Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- systemLogOut -->
        <test-method status="PASS" signature="systemLogin()[pri:0, instance:com.glance.usermanagement.tests.ManageUser@4dfa3a9d]" name="systemLogin" is-config="true" duration-ms="1049" started-at="2016-12-12T22:10:00Z" finished-at="2016-12-12T22:10:01Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- systemLogin -->
        <test-method status="FAIL" signature="GL_UM_12(java.lang.String)[pri:7, instance:com.glance.usermanagement.tests.ManageUser@4dfa3a9d]" name="GL_UM_12" duration-ms="391" started-at="2016-12-12T22:10:01Z" data-provider="GL_UM_12" finished-at="2016-12-12T22:10:01Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[10]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [10] but found [5]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [10] but found [5]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:389)
	at org.testng.Assert.assertEquals(Assert.java:399)
	at com.glance.usermanagement.tests.ManageUser.GL_UM_12(ManageUser.java:111)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:100)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:646)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:811)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1129)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:746)
	at org.testng.TestRunner.run(TestRunner.java:600)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1264)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1189)
	at org.testng.TestNG.runSuites(TestNG.java:1104)
	at org.testng.TestNG.run(TestNG.java:1076)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:152)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:57)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- GL_UM_12 -->
        <test-method status="PASS" signature="systemLogOut()[pri:0, instance:com.glance.usermanagement.tests.ManageUser@4dfa3a9d]" name="systemLogOut" is-config="true" duration-ms="129" started-at="2016-12-12T22:10:01Z" finished-at="2016-12-12T22:10:01Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- systemLogOut -->
        <test-method status="PASS" signature="systemLogin()[pri:0, instance:com.glance.usermanagement.tests.ManageUser@4dfa3a9d]" name="systemLogin" is-config="true" duration-ms="984" started-at="2016-12-12T22:10:01Z" finished-at="2016-12-12T22:10:02Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- systemLogin -->
        <test-method status="PASS" signature="GL_UM_12(java.lang.String)[pri:7, instance:com.glance.usermanagement.tests.ManageUser@4dfa3a9d]" name="GL_UM_12" duration-ms="380" started-at="2016-12-12T22:10:02Z" data-provider="GL_UM_12" finished-at="2016-12-12T22:10:02Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[25]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- GL_UM_12 -->
        <test-method status="PASS" signature="systemLogOut()[pri:0, instance:com.glance.usermanagement.tests.ManageUser@4dfa3a9d]" name="systemLogOut" is-config="true" duration-ms="145" started-at="2016-12-12T22:10:02Z" finished-at="2016-12-12T22:10:03Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- systemLogOut -->
        <test-method status="PASS" signature="systemLogin()[pri:0, instance:com.glance.usermanagement.tests.ManageUser@4dfa3a9d]" name="systemLogin" is-config="true" duration-ms="1172" started-at="2016-12-12T22:10:03Z" finished-at="2016-12-12T22:10:04Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- systemLogin -->
        <test-method status="FAIL" signature="GL_UM_12(java.lang.String)[pri:7, instance:com.glance.usermanagement.tests.ManageUser@4dfa3a9d]" name="GL_UM_12" duration-ms="410" started-at="2016-12-12T22:10:04Z" data-provider="GL_UM_12" finished-at="2016-12-12T22:10:04Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[50]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [50] but found [25]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [50] but found [25]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:389)
	at org.testng.Assert.assertEquals(Assert.java:399)
	at com.glance.usermanagement.tests.ManageUser.GL_UM_12(ManageUser.java:111)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:100)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:646)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:811)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1129)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:746)
	at org.testng.TestRunner.run(TestRunner.java:600)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1264)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1189)
	at org.testng.TestNG.runSuites(TestNG.java:1104)
	at org.testng.TestNG.run(TestNG.java:1076)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:152)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:57)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- GL_UM_12 -->
        <test-method status="PASS" signature="systemLogOut()[pri:0, instance:com.glance.usermanagement.tests.ManageUser@4dfa3a9d]" name="systemLogOut" is-config="true" duration-ms="130" started-at="2016-12-12T22:10:04Z" finished-at="2016-12-12T22:10:04Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- systemLogOut -->
        <test-method status="PASS" signature="systemLogin()[pri:0, instance:com.glance.usermanagement.tests.ManageUser@4dfa3a9d]" name="systemLogin" is-config="true" duration-ms="990" started-at="2016-12-12T22:10:04Z" finished-at="2016-12-12T22:10:05Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- systemLogin -->
        <test-method status="FAIL" signature="GL_UM_12(java.lang.String)[pri:7, instance:com.glance.usermanagement.tests.ManageUser@4dfa3a9d]" name="GL_UM_12" duration-ms="490" started-at="2016-12-12T22:10:05Z" data-provider="GL_UM_12" finished-at="2016-12-12T22:10:06Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[100]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [10] but found [25]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [10] but found [25]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:389)
	at org.testng.Assert.assertEquals(Assert.java:399)
	at com.glance.usermanagement.tests.ManageUser.GL_UM_12(ManageUser.java:111)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:100)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:646)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:811)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1129)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:746)
	at org.testng.TestRunner.run(TestRunner.java:600)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1264)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1189)
	at org.testng.TestNG.runSuites(TestNG.java:1104)
	at org.testng.TestNG.run(TestNG.java:1076)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:152)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:57)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- GL_UM_12 -->
        <test-method status="PASS" signature="systemLogOut()[pri:0, instance:com.glance.usermanagement.tests.ManageUser@4dfa3a9d]" name="systemLogOut" is-config="true" duration-ms="125" started-at="2016-12-12T22:10:06Z" finished-at="2016-12-12T22:10:06Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- systemLogOut -->
      </class> <!-- com.glance.usermanagement.tests.ManageUser -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
