<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" total="4" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="13987" started-at="2016-12-07T11:06:40Z" finished-at="2016-12-07T11:06:54Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="13987" started-at="2016-12-07T11:06:40Z" finished-at="2016-12-07T11:06:54Z">
      <class name="com.glance.usermanagement.tests.ManageUser">
        <test-method status="PASS" signature="testStartUp()[pri:0, instance:com.glance.usermanagement.tests.ManageUser@4dfa3a9d]" name="testStartUp" is-config="true" duration-ms="32" started-at="2016-12-07T16:36:40Z" finished-at="2016-12-07T16:36:40Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testStartUp -->
        <test-method status="PASS" signature="initializeTest()[pri:0, instance:com.glance.usermanagement.tests.ManageUser@4dfa3a9d]" name="initializeTest" is-config="true" duration-ms="5034" started-at="2016-12-07T16:36:40Z" finished-at="2016-12-07T16:36:45Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initializeTest -->
        <test-method status="PASS" signature="systemLogin()[pri:0, instance:com.glance.usermanagement.tests.ManageUser@4dfa3a9d]" name="systemLogin" is-config="true" duration-ms="2167" started-at="2016-12-07T16:36:46Z" finished-at="2016-12-07T16:36:48Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- systemLogin -->
        <test-method status="PASS" signature="GL_UM_09_1(java.lang.String)[pri:3, instance:com.glance.usermanagement.tests.ManageUser@4dfa3a9d]" name="GL_UM_09_1" duration-ms="520" started-at="2016-12-07T16:36:48Z" data-provider="GL_UM_09_1" finished-at="2016-12-07T16:36:48Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[First]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- GL_UM_09_1 -->
        <test-method status="PASS" signature="systemLogOut()[pri:0, instance:com.glance.usermanagement.tests.ManageUser@4dfa3a9d]" name="systemLogOut" is-config="true" duration-ms="142" started-at="2016-12-07T16:36:48Z" finished-at="2016-12-07T16:36:49Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- systemLogOut -->
        <test-method status="PASS" signature="systemLogin()[pri:0, instance:com.glance.usermanagement.tests.ManageUser@4dfa3a9d]" name="systemLogin" is-config="true" duration-ms="1232" started-at="2016-12-07T16:36:49Z" finished-at="2016-12-07T16:36:50Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- systemLogin -->
        <test-method status="FAIL" signature="GL_UM_09_1(java.lang.String)[pri:3, instance:com.glance.usermanagement.tests.ManageUser@4dfa3a9d]" name="GL_UM_09_1" duration-ms="574" started-at="2016-12-07T16:36:50Z" data-provider="GL_UM_09_1" finished-at="2016-12-07T16:36:50Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[Next]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at com.glance.usermanagement.tests.ManageUser.GL_UM_09_1(ManageUser.java:69)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:100)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:646)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:811)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1129)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:746)
	at org.testng.TestRunner.run(TestRunner.java:600)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1264)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1189)
	at org.testng.TestNG.runSuites(TestNG.java:1104)
	at org.testng.TestNG.run(TestNG.java:1076)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:152)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:57)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- GL_UM_09_1 -->
        <test-method status="PASS" signature="systemLogOut()[pri:0, instance:com.glance.usermanagement.tests.ManageUser@4dfa3a9d]" name="systemLogOut" is-config="true" duration-ms="141" started-at="2016-12-07T16:36:50Z" finished-at="2016-12-07T16:36:51Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- systemLogOut -->
        <test-method status="PASS" signature="systemLogin()[pri:0, instance:com.glance.usermanagement.tests.ManageUser@4dfa3a9d]" name="systemLogin" is-config="true" duration-ms="1037" started-at="2016-12-07T16:36:51Z" finished-at="2016-12-07T16:36:52Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- systemLogin -->
        <test-method status="PASS" signature="GL_UM_09_1(java.lang.String)[pri:3, instance:com.glance.usermanagement.tests.ManageUser@4dfa3a9d]" name="GL_UM_09_1" duration-ms="522" started-at="2016-12-07T16:36:52Z" data-provider="GL_UM_09_1" finished-at="2016-12-07T16:36:52Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[Last]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- GL_UM_09_1 -->
        <test-method status="PASS" signature="systemLogOut()[pri:0, instance:com.glance.usermanagement.tests.ManageUser@4dfa3a9d]" name="systemLogOut" is-config="true" duration-ms="175" started-at="2016-12-07T16:36:52Z" finished-at="2016-12-07T16:36:52Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- systemLogOut -->
        <test-method status="PASS" signature="systemLogin()[pri:0, instance:com.glance.usermanagement.tests.ManageUser@4dfa3a9d]" name="systemLogin" is-config="true" duration-ms="1103" started-at="2016-12-07T16:36:52Z" finished-at="2016-12-07T16:36:53Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- systemLogin -->
        <test-method status="FAIL" signature="GL_UM_09_1(java.lang.String)[pri:3, instance:com.glance.usermanagement.tests.ManageUser@4dfa3a9d]" name="GL_UM_09_1" duration-ms="436" started-at="2016-12-07T16:36:53Z" data-provider="GL_UM_09_1" finished-at="2016-12-07T16:36:54Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[Previous]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at com.glance.usermanagement.tests.ManageUser.GL_UM_09_1(ManageUser.java:69)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:100)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:646)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:811)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1129)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:746)
	at org.testng.TestRunner.run(TestRunner.java:600)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1264)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1189)
	at org.testng.TestNG.runSuites(TestNG.java:1104)
	at org.testng.TestNG.run(TestNG.java:1076)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:152)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:57)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- GL_UM_09_1 -->
        <test-method status="PASS" signature="systemLogOut()[pri:0, instance:com.glance.usermanagement.tests.ManageUser@4dfa3a9d]" name="systemLogOut" is-config="true" duration-ms="63" started-at="2016-12-07T16:36:54Z" finished-at="2016-12-07T16:36:54Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- systemLogOut -->
      </class> <!-- com.glance.usermanagement.tests.ManageUser -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
